# fly.toml app configuration file generated for llm-extract on 2025-02-25T06:44:42+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'llm-extract'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "5s"
    [http_service.checks.headers]
      Content-Type = "application/json"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
